# Site settings
baseURL = "/"
languageCode = "en-us"
title = "Association TeDua"
theme = "forty"

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Enter your disqus shortname to enable comments
disqusShortname = ""

#versioning hugo 0.60 et au-dessus nécessite cette option pour que le html s'affiche bien dans les fichiers écrits en markdown 
[markup.goldmark.renderer]
   unsafe= true

[params]
  # You can use Markdown syntax for urls [text](//url.to/source)
  # To create multi-line text in strings use the """example Text""" format
  #
  # All icons using Fontawesome's icon font. Look at fontawesome.io/icons
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # Provide your metadata here.
  name = "Association TeDua"
  description = "Face à la création de spectacles de théâtre et de clown, et par la discipline du jeu, l'association Tedua invite chacun à découvrir l'autre."

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"

  # Just a custom image variable, please define it in .md files for content.
  image = ""

  # 404 error customization
  [params.error404]
    heading = "Cette page n'a pas pu être trouvée"
    text = "Visiter plutôt *www.association-tedua.fr* pour y trouver la bonne information, ou nous contacter directement à l'adresse suivante: *diffusion@association-tedua.fr*."

  # Navigation Section
  [params.navigation]
    menu = "Menu"
    # Optional logo as brand stored in img/
    #logo = "logo.jpg"

   

    # Add custom links here by uncommenting code below. To remove links just delete
    # the [[params.navigation.links]] map associated with that link. Copy and paste
    # code below if you need more links. Buttons work in the same way.
    # [[params.navigation.links]]
    #    name = "NameOfLink"
    #    url = "UrlOfLink"

 	[[params.navigation.links]]
      name = "Accueil"
      url = "#"

    [[params.navigation.links]]
      name = "Spectacles"
      url = "accueil/spectacles-creations"

    [[params.navigation.links]]
      name = "Formations : la discipline du jeu"
      url = "accueil/la-discipline-du-jeu-formations-theatre-clown"

    [[params.navigation.links]]
      name = "Résidence & festival : KIJOU?"
      url = "accueil/kijou"

    [[params.navigation.links]]
      name = "Informations pratiques"
      url = "accueil/informations-pratiques"

    # Button Style 1
    [[params.navigation.button1]]
      name = "Journal de bord"
      url = "blogs"

  # Banner section
  [params.banner]
    # To change the background image on the homepage banner, replace 'banner.jpg' in
    # the 'static/img' folder.
    title = "TEDUA"
    subtitle = "Face à la création de spectacles de théâtre et de clown, et par la discipline du jeu, l'association Tedua invite chacun à découvrir l'autre."
    buttonText = "VIENS!"


  # Tiles Section
  [params.tiles]
    enable = true
    # Display your showcases here.

    [[params.tiles.showcase]]
      title = "SPECTACLES"
      subtitle = "Liste des spectacles de théatre ou de clown, prochaines dates de représentation. Tous publics : enfants, adultes, familles. [---cliquer ici-->]"
      image = "collage_aurillac_2019.jpg"
      url = "accueil/spectacles-creations"

    [[params.tiles.showcase]]
      title = "FORMATIONS : 'LA DISCIPLINE DU JEU' "
      subtitle = "Ateliers hebdomadaires, Weekends de stages, préparation aux grandes écoles...'La discipline du jeu' est enseignée par Jonathan Dupui. Novice, initié, amateur ou pro: bienvenue ! [---cliquer ici-->]"
      image = "eleves1.png"
      url = "accueil/la-discipline-du-jeu-formations-theatre-clown"

    [[params.tiles.showcase]]
      title = "RÉSIDENCE-FESTIVAL"
      subtitle = "Entre résidence ouverte et festival tous publics, 'KIJOU?' s'est déroulé sur 6 jours au théâtre du Cerisier :  jouer, créer, accueillir, être ensemble. Re-découvrir l'espace du public. [---cliquer ici-->]"
      image = "pic04.png"
      url = "accueil/kijou"

  [[params.tiles.showcase]]
      title = "INFOS PRATIQUES"
      subtitle = "Calendrier des activités de TeDua, visages de l'équipe motrice et des bénévoles, lieux des activités et des rencontres, statuts et fonctionnement général de l'association,... [---cliquer ici-->]"
      image = "stages.jpg"
      url = "accueil/informations-pratiques"

 
    # You can make more showcases by copy and pasting the code above

  [params.blog]
    # All blogs defined in their own files. You can find example blogs
    # at 'exampleSite/content/blogs'. Copy the 'blogs' folder into the 'content' directory
    # at the root of this Hugo site.
    # For more information take a look at the README.
    # To add more blogs just copy and paste the code.

  # Section Type Two
  [params.two]
    enable = true
    title = "Journal de bord"
    subtitle = " "
    buttonText = "Actualités et textes écrits par des membres de l'association"
    url = "blogs"


  # Contact section
  [params.contact]
    enable = true
    buttonSend = "envoyer le message --> "
    buttonClear = "Effacer"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below and uncomment
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    # formEmail = "example@domain.com"

    # Contact Section
    # You can add multiple emails, phone numbers, or addresses
    # by copying the corresponding map with frontmatter code.
    
    [[params.contact.email]]
    title = "Email"
    email = "diffusion@association-tedua.fr"

    [[params.contact.phone]]
    title = "Téléphone (Anne Lucie Dumay)"
    phone = "06 15 60 97 04"

    [[params.contact.address]]
    title = "Adresse de l'association TeDua"
    street = "4 cité de la Digue, avenue Gaston Cabannes"
    city = "33 270 Floirac (Bordeaux Métropole)"

  # Footer section
  [params.footer]
    enable = true
    copyright = "[copyleft] Assocation TeDua "

    # Uses font awesome icons

    [[params.footer.social]]
      icon = "fa-facebook"
      url= "https://www.facebook.com/groups/386241745191819/"
      label = "Facebook"


    [[params.footer.quicklinks]]
      text = "Design:"
      url= "https://github.com/habsinn/association-tedua"
      alt = "Les Ethers Fertiles"
